version: '3'

services:
  postgres:
    build: dockerfiles/postgres
    volumes:
      - ./api/postgres_data:/var/lib/postgresql/data
    env_file:
      - env_file
    networks:
      - db_nw

  flask:
    build: dockerfiles/flask
    volumes:
      - ./api:/opt/services/flaskapp/src
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flask

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data:
