version: '3'

services:
  postgres:
    image: postgres:10.1
    volumes:
      - "./api/postgres_data:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw
    hostname: passq-postgres

  flask:
    build: dockerfiles/flask
    volumes:
      - ./api:/opt/services/flaskapp/src
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres
    hostname: passq-flask

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - flask
    hostname: passq-nginx

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data: