version: '3'

services:
  postgres:
    image: postgres:10.1
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw

  flask:
    build: flask
    volumes:
      - ../pass-culture-flask:/opt/services/flaskapp/src
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "5090:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - flask

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data: