version: '3.2'

services:
  postgres:
    image: postgres:10.1
    volumes:
      - "./api/postgres_data:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw

  flask:
    build: dockerfiles/flask
    volumes:
      - ./api:/opt/services/flaskapp/src
      - type: bind
        source: ./api/ftp_mirrors
        target: /opt/services/flaskapp/src/ftp_mirrors
        read_only: true
    env_file:
      - env_file
      - ${ENV:-development}_env_file
    environment:
      - ENV=${ENV:-development}
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    networks:
      - web_nw
    depends_on:
      - flask

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  postgres_data:
